---
language: jvm
dist: xenial
jdk:
  - openjdk11

stages:
  - build
  - test
  - name: publish
    if: branch = main

addons:
  sonarcloud:
    organization: "johnnystarr_jvm65"
    token:
      secure: ${SONAR_TOKEN}

jobs:
  include:
    - stage: build
      script: ./gradlew jar --scan
    - stage: test
      script:
        - ./gradlew test
        - sonar-scanner
    - stage: publish
      script: ./gradlew publish