---
language: java
os:
  - linux
  - osx

jdk:
  - openjdk11
  - oraclejdk11

before_install:
  - openssl aes-256-cbc -K $encrypted_6afd0fc9428e_key -iv $encrypted_6afd0fc9428e_iv -in secring.gpg.enc -out lib/secring.gpg -d
  - openssl aes-256-cbc -K $encrypted_2afbb999f001_key -iv $encrypted_2afbb999f001_iv -in gradle.properties.enc -out gradle.properties -d

stages:
  - build
  - test
  - name: release
    if: branch = main AND type NOT IN (pull_request)

jobs:
  include:
    - stage: build
      script: ./gradlew jar --scan
    - stage: test
      script:
        - ./gradlew test
        - bash <(curl -s https://codecov.io/bash)
    - stage: release
      script: ./gradlew build uploadArchives