---
language: jvm
dist: xenial
jdk:
  - openjdk11

stages:
  - build
  - test
  - name: publish
    if: branch = main

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

jobs:
  include:
    - stage: build
      script: ./gradlew jar --scan
    - stage: test
      script:
        - ./gradlew test
        - ./cc-test-reporter after-build -t jacoco -o build/test-results/*.xml --exit-code $TRAVIS_TEST_RESULT
    - stage: publish
      script: ./gradlew publish