---
language: java
os:
  - linux
  - osx

jdk:
  - openjdk11
  - oraclejdk11

stages:
  - build
  - test
  - name: publish
    if: branch = main
  - release
    if: branch = main

jobs:
  include:
    - stage: build
      script: ./gradlew jar --scan
    - stage: test
      script:
        - ./gradlew test
        - bash <(curl -s https://codecov.io/bash)
    - stage: publish
      script: ./gradlew publish
    - stage: release
      script: ./gradlew assembleDist
      deploy:
        provider: releases
        api_key: ${GITHUB_TOKEN}
        file_glob: true
        file: build/distributions/*
        skip_cleanup: true
        on:
          branch: main
          tags: true