---
language: jvm
dist: xenial
jdk:
  - openjdk11

stages:
  - build
  - test
  #- name: publish
  #  if: branch = main
  - release

jobs:
  include:
    - stage: build
      script: ./gradlew jar --scan
    - stage: test
      script:
        - ./gradlew test
        - bash <(curl -s https://codecov.io/bash)
    - stage: release
      provider: release
      api_key: ${GITHUB_TOKEN}
      file: ./build/distributions/*.tar ./build/distributions/*.zip

    #- stage: publish
    #  script: ./gradlew publish