---
language: java
os:
  - linux
  - osx

jdk:
  - openjdk11
  - oraclejdk11

before_install: openssl aes-256-cbc -K $encrypted_6afd0fc9428e_key -iv $encrypted_6afd0fc9428e_iv -in secring.gpg.enc -out secring.gpg -d

stages:
  - build
  - test
  - name: publish
    if: branch = main
  - release

jobs:
  include:
    - stage: build
      script: ./gradlew jar --scan
    - stage: test
      script:
        - ./gradlew test
        - bash <(curl -s https://codecov.io/bash)
    - stage: publish
      script: ./gradlew uploadArchives -Psigning.keyId=${SIGNING_KEY_ID} -Psigning.password=${SIGNING_PASSWORD} -PossrhUsername=${OSSRH_USERNAME} -PossrhPassword=${OSSRH_PASSWORD}
    - stage: release
      script: ./gradlew assembleDist
      deploy:
        provider: releases
        api_key: ${GITHUB_TOKEN}
        file_glob: true
        file: build/distributions/*
        skip_cleanup: true
        on:
          branch: main
          tags: true