---
language: jvm
dist: xenial
jdk:
  - openjdk11

stages:
  #- build
  #- test
  #- name: publish
  #  if: branch = main
  - deploy
    #if: branch = main

jobs:
  include:
    #- stage: build
    #  script: ./gradlew jar --scan
#    - stage: test
#      script:
#        - ./gradlew test
#        - bash <(curl -s https://codecov.io/bash)
    #- stage: publish
    #  script: ./gradlew publish
    - stage: deploy
      script: ./gradlew build
      deploy:
        provider: releases
        api_key: ${GITHUB_TOKEN}
        file_glob: true
        file: ./build/distributions/*.*
        on:
          all_branches: true
          tags: false